### ISSUE TITLE
Bundle Loot causing crash

### ISSUE THREAD

**Issue by Muffintiem** [kwpugh/ward_blocks_fabric#1]
I've been testing this mod to see if I want to add it and I noticed that the Loot Block drops bundles. However when I tried using the bundle I get a crash. I think it might be a conflict with either the Treasure Bag or Gem Bag from More Gems. I can fix it for myself but I just thought I'd let you know so you could remove them from the loot list.

**Comment by kwpugh** [comment]
Crash report?

**Comment by Muffintiem** [comment]
There wasn't any crash report since it did that freeze up thing where I'd need to use task manager. Anyways I found out that what's causing the bundle to crash is actually a different mod I added to change the stack size. So really the only thing you could do on your end would be to remove the bundle from the loot table but idk if you would want to.

**Comment by kwpugh** [comment]
Good to know if someone else encounters it.
