### ISSUE TITLE
[1.18.1] Sync server config and client config

### ISSUE THREAD

**Issue by Antoninecek** [kwpugh/ward_blocks_fabric#2]
When I allow ward blocks on server side, every client has to manually update their config to allow them too.

**Comment by kwpugh** [comment]
Cloth Config makes no distinction between server and client configs, so they must both be the same.

**Comment by Antoninecek** [comment]
Sorry, I'm kinda new to configuring mc, so I don't fully understand your statement. I'm playing AQM2. Author disabled some ward blocks. Because we used them before he disabled them, I've allowed them in our server config. With every modpack update, we have to update our clients to match server manually. I've been told that mod creators can implement sync between server and client and it's common operation.

**Comment by kwpugh** [comment]
I'm not aware of any way to sync client and server config files. I will ask around.

**Comment by kwpugh** [comment]
Still not a feature in Cloth Config.  The author is working one it.

<img width="577" alt="Screen Shot 2022-01-24 at 6 09 32 PM" src="https://user-images.githubusercontent.com/8809210/150886228-b0563991-ee19-458c-9b42-80c0babf4b83.png">

**Comment by kwpugh** [comment]
At present, there is not built-in method for Cloth Config to distinguish between server and client configs.  Also, block registration happens very early in game load such that my code cannot detect/force server vs client side.  I have to wait until Cloth Config adds the feature.  You may have been getting info about Forge, which has server/client config types built in.

**Comment by Antoninecek** [comment]
Ok, I'll wait then, thank you.
